services:
  redis:
    image: redis:alpine
    container_name: media-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  media-app:
    build: .
    container_name: media-app
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./processed:/app/processed
    networks:
      - app_network


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./processed:/app/processed
    restart: unless-stopped
    depends_on:
      - media-app
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge